### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bebatut** [dparks1134/FragmentClassificationPackage#3]
Hello,

I would like to develop a conda package for this tool (via the [BioConda project](https://bioconda.github.io/)). The idea is to ease its installation and to make it available as dependency for other packages using it (such as MetAMOS).
But, I need to know if we could share your tool with conda: I could not find any license here.

Can we develop a conda package for this tool? Could be you please give more information about the license you want to be associated with your tool?

Thank you a lot for your help,

Bérénice

**Comment by donovan-h-parks** [comment]
Hello. The FCP is released under the GNU General Public License v3.

**Comment by bebatut** [comment]
Thanks a lot for your quick answer !
I will tell you when the conda package will be available for your tool 😄
